<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>page</string>
		<string>html</string>
	</array>
	<key>name</key>
	<string>Visualforce</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#apex-inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#apex-block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>apex-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:^\s+)?(&lt;)(apex:\w+\s)(?=[^/&gt;]*&gt;)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.page</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Block apex tags &lt;apex:pageBlock&gt; ... &lt;/apex:pageBlock&gt;</string>
					<key>end</key>
					<string>(&lt;/)(apex:\w+)(&gt;)</string>
					<key>name</key>
					<string>block.apex.page</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#apex-inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-apex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>apex-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(apex:\w+\s)(?=[^&gt;]*/&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.page</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.page</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Inline apex tags &lt;apex:actionfunction ... /&gt;</string>
					<key>end</key>
					<string>(/&gt;)</string>
					<key>name</key>
					<string>inline.apex.entity.tag.page</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-apex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.page</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+=)</string>
					<key>name</key>
					<string>apex.body.page</string>
				</dict>
			</array>
		</dict>
		<key>embedded-apex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{!)(?=.*\})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.page</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>{! ... }</string>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.page</string>
						</dict>
					</dict>
					<key>name</key>
					<string>embedded.apex.entity.tag.page</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-global-variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-global-function</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>embedded-global-function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([A-Z]+\()(?=.*\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded Resources</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-global-variables</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>embedded-global-variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>$Resource, $Component</string>
					<key>match</key>
					<string>(\$\w+)([\.\w+]+)</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.visualforce</string>
	<key>uuid</key>
	<string>4ca6a18d-a67f-4216-b60c-796faa08afe8</string>
</dict>
</plist>
